trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- script: echo "Iniciando pipeline"
  displayName: 'Start'

- task: DockerInstaller@0
  inputs:
    dockerVersion: '20.10.7'

- script: |
    docker build -t minha-api .
  displayName: 'Build Docker'

- script: |
    docker run -d -p 5000:5000 minha-api
    sleep 15
    docker ps
    echo "Container em execucao com sucesso"
  displayName: 'Run e Validar Container'
